services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jiriki-nextjs
    args:
        - NEXT_PUBLIC_SANITY_PROJECT_ID=${NEXT_PUBLIC_SANITY_PROJECT_ID}
        - NEXT_PUBLIC_SANITY_DATASET=${NEXT_PUBLIC_SANITY_DATASET}
        - NEXT_PUBLIC_SANITY_API_VERSION=${NEXT_PUBLIC_SANITY_API_VERSION}
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        - NEXT_PUBLIC_CLERK_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_SIGN_IN_URL}
        - NEXT_PUBLIC_CLERK_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_SIGN_UP_URL}
    restart: always
    environment: 
      - NODE_ENV=production
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - SANITY_API_TOKEN=${SANITY_API_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jiriki.rule=Host(`jiriki.tech`) || Host('www.jiriki.tech')"
      - "traefik.http.routers.jiriki.entrypoints=websecure"
      - "traefik.http.routers.jiriki.tls.certResolver=letsencrypt"
      - "traefik.http.services.jiriki.loadbalancer.server.port=3000"
networks:
  dokploy-network:
    external: true
